from bs4 import BeautifulSoup
from pathlib import Path

p = Path('week02.html')
soup = BeautifulSoup(p.read_text(encoding='utf-8'), 'html.parser')
hw = soup.find('section', id='homework')
if not hw:
    raise SystemExit('homework section not found')

new_html = '''<section id="homework"><div class="head"><div><span class="label">Formative homework · real source</span><h2>Vocabulary Evidence Log — Real Electrical Engineering Reading</h2></div><p>Everyone will work from the same open-access Electrical Engineering page.</p></div><div class="home"><div class="source"><strong>Required reading:</strong> Engineering LibreTexts — <em>3.4: Electric Circuits and Interconnection Laws</em>.<br/><br/><a class="open" href="https://eng.libretexts.org/Bookshelves/Electrical_Engineering/Introductory_Electrical_Engineering/Electrical_Engineering_%28Johnson%29/03%3A_Analog_Signal_Processing/3.04%3A_Electric_Circuits_and_Interconnection_Laws" target="_blank" rel="noopener">Open the real reading ↗</a></div><h3 style="margin-top:18px">Choose Five Unfamiliar Words</h3><p>Read from the beginning of the page through the section <strong>Kirchhoff's Current Law (KCL)</strong>. Choose <strong>five words that are genuinely unfamiliar to you</strong>. They may be academic words or Electrical Engineering terms, but do not choose symbols, equations, or words you already know well.</p><ol><li>Copy only the <strong>sentence or short context</strong> containing the word.</li><li>Read to the end of that sentence and the <strong>next sentence</strong>.</li><li>Identify the <strong>clue type</strong>: definition, exemplification, contrast, or general knowledge/context.</li><li>Write your <strong>guessed meaning before checking a dictionary</strong>.</li><li>Verify the meaning and mark your guess <strong>close / partly close / different</strong>.</li></ol><div class="takeaway"><strong>Worked example — do not use this as one of your five:</strong><br/><strong>redundant</strong> — the page explains that one KCL equation can be obtained from the others and therefore can be discarded. From this context, <em>redundant</em> means <strong>unnecessary because the same information is already provided elsewhere</strong>. The clue comes from the surrounding explanation.</div><div class="table-scroll" style="margin-top:14px"><table><tr><th>Word</th><th>Sentence / short context</th><th>Clue type + evidence</th><th>My guessed meaning</th><th>Verified meaning</th><th>Close?</th></tr><tr><td>1.</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>2.</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>3.</td><td></td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>4.</td><td></td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>5.</td><td></td><td></td><td></td><td></td><td></td><td></td></tr></table></div><div class="submission"><strong>Bring to Week 3:</strong> your completed five-word log. This is formative practice, not the graded 5-mark homework.</div></div></section>'''

hw.replace_with(BeautifulSoup(new_html, 'html.parser').find('section'))
p.write_text(str(soup), encoding='utf-8')
